language: node_js
os: linux
dist: trusty
group: travis_lts

addons:
  chrome: stable

node_js:
  - '10'

notifications:
  email:
    recipients:
      - sebastien.jourdain@kitware.com
    on_success: change
    on_failure: always

cache:
  directories:
    - "$HOME/.npm"
    - documentation/build-tmp

before_install:
  - sudo apt-get install -y libgif-dev

install:
  - npm ci

script:
  - if [ "$TRAVIS_EVENT_TYPE" == "push" ] && [ "$TRAVIS_BRANCH" == "master" ]; then ./build/travis-release.sh; fi
